### ISSUE TITLE
"roots new" current directory

### ISSUE THREAD

**Issue by peduarte** [jenius/roots.cx#36]
Hey guys,

First, awesome project. 
Can't wait to start using it.

But before that, I have one question, might seem stupid, but here's what I'm trying to do:

I've got an existing repo, which contains my personal site.
I've created a new orphan branch (v2) - where I want to make a new one using roots.

In this new branch, I am trying to create a new roots project in the current directory, rather than a new folder (project name).

I am trying the following:
`roots new .`
but I get some errors. attached a screen shot for reference:
![screenshot 2015-02-02 15 51 37](https://cloud.githubusercontent.com/assets/372831/6003410/6ed41e7e-aaf3-11e4-9e95-de0d7a5b59f6.png)

Could you advise on what's the best approach?

Thanks!

**Comment by jenius** [comment]
Hey Pedro,

Sure, make sure to read the error message! This is a permissions error, the permissions are not set up correctly on your computer to do what you are trying to do. There are two ways to resolve this:

1. Use `sudo` and run the command again
2. Fix the permissions so that they are correct using `chown`

The first one is easier but will cause more problems down the road. The second one is harder but will make sure there are no issues like this again. I'm going to close this issue because it's not a problem with the old version of the roots website, and it's also not a problem with roots.

I see a lot of people struggling with unix permissions though, so I'm going to add a section to the roots docs site (current version can be [found here](https://github.com/carrot/roots-www)) trying to break down how to learn more about permissions.

**Comment by peduarte** [comment]
Got it!
Thanks a lot!

**Comment by jescalan** [comment]
@peduarte just added a small section to the docs about this. Hope you can get it resolved soon!

http://roots.cx/docs/error#eacces-permission-denied

**Comment by peduarte** [comment]
:+1:
