### ISSUE TITLE
Is there a post.next and post.previous attributes?

### ISSUE THREAD

**Issue by ganar** [jenius/roots.cx#37]
I understand that _Jekill_ has this attributes—post.next and post.previous—, but when I try to reach post.previous.imagemain I get 

```
Cannot read property 'imagemain' of undefined
```

Is there a way to do this with roots?

**Comment by ganar** [comment]
@jenius confirmed that this is not possible, neither in this version, nor in version 3

**Comment by jescalan** [comment]
Yup, sorry! The best way to handle moving between posts is to use javascript along with dynamic content's JSON export support. The reasoning for this has been hashed out in a number of issues that can be found in the dynamic content repo.

https://github.com/carrot/roots-dynamic-content/blob/master/docs/intro.md#exporting-dynamic-content-as-json

**Comment by ganar** [comment]
I know this is a _noob_ question —sorry about that— but you do talk about  `JSON.stringify(site)` [in this post about building a blog in roots (v2)](http://carrot.is/coding/roots_blog_tutorial).

I don't know what I'm doing wrong, but I don't get a result when using the method described:

> **pro tip:** If you are trying to see the contents of any local object in jade, you can use `= JSON.stringify(whatever)` to have it print the contents. You could do this with the site variable to peek at all the dynamic content. If you tried printing it without stringify, it would print as `[Object object]` like javascript always does.

**How would you then use this method to include the _next_ and _previous_ buttons in the content of a post?** I'm still dumbfounded. Any help is deeply appreciated

**Comment by jescalan** [comment]
So `site` is not a strict json object. You want to pull `site.posts` or whatever you called you folder. However you will not be able to have next and previous buttons in the contents of a post even with this modification.

Why is this? Think about how the posts are compiled to static. Roots goes through the posts folder and tries to compile them as quickly as possible. So when any individual post is compiled, it's unlikely that both the post before and after it have already been compiled and finished. In fact, it's not possible that for every post, the next and previous post could be compiled, without compiling everything twice, which is a waste of resources. This is the difference between a static and dynamic site. With a dynamic site, it's trivial to have this functionality, since the page is compiled on demand, whereas with a static site, the requirements are different.

In v3, you can do this with json content support using client-side javascript as described above. In v2 you can't do it at all. Overall, the best solution is to remove this type of functionality and simply have a "back to index" type button instead. People rarely will just page through blog post after blog post, reading them all in order anyway. In fact, most people won't even read an entire single blog post, at best they will skim it, looking for something they are after.
